name: nyphil-program-generator
channels:
  - defaults
dependencies:
  - click
  - flask
  - flask-cors
  - pandas
  - pip
  - pymysql
  - python=3.7
  - python-Levenshtein
  - requests
  - scikit-learn
  - SQLAlchemy
  - pip:
    - fuzzywuzzy
    - psycopg2-binary
    - python-dotenv
