INSTRUMENT_CATEGORIES = {
    "Actor": "Actor",
    "Mime": "Actor",
    "Actor and Dancer": "Actor",
    "Trumpet": "Brass",
    "French Horn": "Brass",
    "Trombone": "Brass",
    "Tuba": "Brass",
    "Cornet": "Brass",
    "Bass Trombone": "Brass",
    "Euphonium": "Brass",
    "Tenor Trombone": "Brass",
    "Tenor Tuba": "Brass",
    "Dancer": "Dancer",
    "Choreographer": "Dancer",
    "Dancer; Choreographer": "Dancer",
    "Dancer; Dancer; Choreographer; Choreographer": "Dancer",
    "Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Choreographer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Scenic Design": "Dancer",
    "Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer": "Dancer",
    "Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Dancer; Choreographer; Dancer; Dancer": "Dancer",
    "Chorus": "Ensemble",
    "Ensemble": "Ensemble",
    "Boys Choir": "Ensemble",
    "Children's Chorus": "Ensemble",
    "Orchestra": "Ensemble",
    "Mens Chorus": "Ensemble",
    "Womens Chorus": "Ensemble",
    "String Quartet": "Ensemble",
    "Ensemble, Featured": "Ensemble",
    "Band": "Ensemble",
    "Jazz Ensemble": "Ensemble",
    "Guest Orchestra": "Ensemble",
    "Brass Quintet": "Ensemble",
    "Jazz Trio": "Ensemble",
    "Trombone Choir": "Ensemble",
    "Piano": "Keyboard",
    "Organ": "Keyboard",
    "Harpsichord": "Keyboard",
    "Electric Organ": "Keyboard",
    "Keyboard": "Keyboard",
    "Duo Pianos": "Keyboard",
    "Duo-Art Piano": "Keyboard",
    "Percussion": "Percussion",
    "Drum": "Percussion",
    "Drum Set": "Percussion",
    "Timpani": "Percussion",
    "Xylophone": "Percussion",
    "Percussion Ensemble": "Percussion",
    "Narrator": "Speaker",
    "Speaker": "Speaker",
    "Host": "Speaker",
    "Commentator": "Speaker",
    "Violin": "String",
    "Cello": "String",
    "Viola": "String",
    "Guitar": "String",
    "Harp": "String",
    "Double Bass": "String",
    "Lute": "String",
    "Mandolin": "String",
    "Jazz Bass": "String",
    "Viola da Gamba": "String",
    "Viola d'amore": "String",
    "Soprano": "Voice",
    "Vocalist": "Voice",
    "Tenor": "Voice",
    "Baritone": "Voice",
    "Mezzo-Soprano": "Voice",
    "Bass": "Voice",
    "Contralto": "Voice",
    "Singer": "Voice",
    "Bass-Baritone": "Voice",
    "Alto": "Voice",
    "Contrabass": "Voice",
    "Boy Soprano": "Voice",
    "Child Soprano": "Voice",
    "Solo Voice": "Voice",
    "Countertenor": "Voice",
    "Unspecified Voice": "Voice",
    "Folk Singer": "Voice",
    "Clarinet": "Woodwind",
    "Flute": "Woodwind",
    "Oboe": "Woodwind",
    "Bassoon": "Woodwind",
    "English Horn": "Woodwind",
    "Alto Saxophone": "Woodwind",
    "Bass Clarinet": "Woodwind",
    "Piccolo": "Woodwind",
    "Saxophone": "Woodwind",
    "Oboe d'Amore": "Woodwind",
    "Tenor Saxophone": "Woodwind",
    "Basset Horn": "Woodwind",
    "Contrabassoon": "Woodwind",
    "Alto Flute": "Woodwind",
    "E-Flat Clarinet": "Woodwind",
    "Baritone Saxophone": "Woodwind",
    "Flute/Piccolo": "Woodwind",
    "Oboe / English Horn": "Woodwind",
    "Clarinet / Bass Clarinet": "Woodwind",
}
